"""
Module to export the Schema as an graphqls file and a json introspection file.
To be executed on it's own.
"""
import graphene
import json
import pkg_resources

from riptide_mission_control.graphql_entities.query import Query
from riptide_mission_control.graphql_entities.mutation import Mutation
from riptide_mission_control.graphql_entities.subscription import Subscription


def main():
    schema = graphene.Schema(query=Query, mutation=Mutation, subscription=Subscription)

    with open(pkg_resources.resource_filename(__name__, 'schema.graphqls'), 'w') as f:
        f.writelines(["# Auto-generated schema. Do not edit. Generated by schema_printer.\n",
                      "# As a dev you can run schema_printer to update, otherwise will be updated by CI.\n",
                      str(schema)])

    with open(pkg_resources.resource_filename(__name__, 'schema.json'), 'w') as f:
        introspection_schema = schema.introspect()
        introspection_schema['__comment'] = \
            "Auto-generated schema. Do not edit. Generated by schema_printer. " \
            "As a dev you can run schema_printer to update, otherwise will be updated by CI."
        json.dump(introspection_schema, f, indent=4, sort_keys=True)


if __name__ == "main":
    main()
